### ISSUE TITLE
det2_half.caffemodel 这是模型是不是传错了？

### ISSUE THREAD

**Issue by MaeThird** [szad670401/Fast-MTCNN#2]
det2_half.caffemodel 用Caffe或者NCNN都导不出来，是不是传错了？

**Comment by wavelet2008** [comment]
群主那里指定fp16 啊  我安装opencv3.3 
Net cv::dnn::readNetFromCaffe	(	const char * 	bufferProto,
size_t 	lenProto,
const char * 	bufferModel = NULL,
size_t 	lenModel = 0 
)
